### ISSUE TITLE
support for macos

### ISSUE THREAD

**Issue by c1c2ai** [Norbert515/flutter_ide#28]
would you release installable for macos?

**Comment by Norbert515** [comment]
Unfortunately, I don't own a mac but feel free to clone the repository and run it yourself!

**Comment by Pilfer** [comment]
Hey, it's worth noting that you can use [Github Actions](https://github.com/Norbert515/flutter_ide/actions) to build for OSX without actually owning a Mac. With robust enough tests, it should still produce a functional app! :)

That being said, I can't get this to build locally with the latest version on my Mac. I'll give it another shot later today as this project looks like it'd be very useful to mock up some UI's. I'll give it a try on my windows machine otherwise!

**Comment by Norbert515** [comment]
Indeed. I used to build it for Windows using Github Actions too.
I'm not actively working on this project right now but I'm happy to assist with issues and talk about potential PRs! :)

**Comment by orestesgaolin** [comment]
I can give a try and build installable version on macOS but no sooner than
in couple of days.

Best,
Dominik Roszkowski

sob., 9 maj 2020, 12:53 użytkownik Norbert Kozsir <notifications@github.com>
napisał:
